### ISSUE TITLE
Server doesn't start after installing

### ISSUE THREAD

**Issue by Cattn** [hkva/fabric-discord-integration#22]
It has been properly configured with channel + user afaik, but server doesn't start

Platform: Ubuntu

Config: 

```{
  "token": "...",
  "commandPrefix": "mc!",
  "relayChannelIDs": [ 1034272152440021042 ],
  "rconUserIDs": [ 523927057722376204 ],
  "disableMentions": false,
  "discordMessageFormat": "[$USERNAME] $MESSAGE",
  "chatMessageFormat": "**\u003c$NAME\u003e** $MESSAGE",
  "systemMessageFormat": "**$MESSAGE**"
}
```

Error:

java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'discord'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.10.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: kotlin/Unit
        at okhttp3.Dispatcher.setMaxRequestsPerHost(Dispatcher.kt:70) ~[com_squareup_okhttp3_okhttp-4.9.3-6e8ae270ceeed625.jar:?]
        at net.dv8tion.jda.internal.utils.IOUtil.newHttpClientBuilder(IOUtil.java:107) ~[net_dv8tion_jda-5.0.0-beta.1-3b6d5ee675679d7d.jar:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1762) ~[net_dv8tion_jda-5.0.0-beta.1-3b6d5ee675679d7d.jar:?]
        at dev.hkva.discord.DiscordBot.connect(DiscordBot.java:35) ~[fabric-discord-integration-1.2.6.jar:?]
        at dev.hkva.discord.DiscordIntegrationMod.tryReconnect(DiscordIntegrationMod.java:98) ~[fabric-discord-integration-1.2.6.jar:?]
        at dev.hkva.discord.DiscordIntegrationMod.onInitializeServer(DiscordIntegrationMod.java:67) ~[fabric-discord-integration-1.2.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: kotlin.Unit
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at okhttp3.Dispatcher.setMaxRequestsPerHost(Dispatcher.kt:70) ~[com_squareup_okhttp3_okhttp-4.9.3-6e8ae270ceeed625.jar:?]
        at net.dv8tion.jda.internal.utils.IOUtil.newHttpClientBuilder(IOUtil.java:107) ~[net_dv8tion_jda-5.0.0-beta.1-3b6d5ee675679d7d.jar:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1762) ~[net_dv8tion_jda-5.0.0-beta.1-3b6d5ee675679d7d.jar:?]
        at dev.hkva.discord.DiscordBot.connect(DiscordBot.java:35) ~[fabric-discord-integration-1.2.6.jar:?]
        at dev.hkva.discord.DiscordIntegrationMod.tryReconnect(DiscordIntegrationMod.java:98) ~[fabric-discord-integration-1.2.6.jar:?]
        at dev.hkva.discord.DiscordIntegrationMod.onInitializeServer(DiscordIntegrationMod.java:67) ~[fabric-discord-integration-1.2.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
        ... 7 more

**Comment by hkva** [comment]
Thanks for reporting the crash. Which Fabric API version are you using?

**Comment by hkva** [comment]
It looks like the latest build pulled a new version of a JDA dependency (okhttp) that requires Kotlin language support. These were supposed to be locked, not sure how that happened.

For now, installing the Fabric language module for Kotlin should fix your issue: https://github.com/FabricMC/fabric-language-kotlin/releases

**Comment by Cattn** [comment]
Can confirm this fixes it. Thank you

**Comment by Cattn** [comment]
Should we leave this open and rename it until it's fixed?

**Comment by hkva** [comment]
Yes
